<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::truncate();
        $countries = [
    ['code' => 'AF', 'name' => 'Afganistan'],
    ['code' => 'AX', 'name' => 'Kepulauan Aland'],
    ['code' => 'AL', 'name' => 'Albania'],
    ['code' => 'DZ', 'name' => 'Aljazair'],
    ['code' => 'AS', 'name' => 'Samoa Amerika'],
    ['code' => 'AD', 'name' => 'Andorra'],
    ['code' => 'AO', 'name' => 'Angola'],
    ['code' => 'AI', 'name' => 'Anguilla'],
    ['code' => 'AQ', 'name' => 'Antarktika'],
    ['code' => 'AG', 'name' => 'Antigua dan Barbuda'],
    ['code' => 'AR', 'name' => 'Argentina'],
    ['code' => 'AM', 'name' => 'Armenia'],
    ['code' => 'AW', 'name' => 'Aruba'],
    ['code' => 'AU', 'name' => 'Australia'],
    ['code' => 'AT', 'name' => 'Austria'],
    ['code' => 'AZ', 'name' => 'Azerbaijan'],
    ['code' => 'BS', 'name' => 'Bahama'],
    ['code' => 'BH', 'name' => 'Bahrain'],
    ['code' => 'BD', 'name' => 'Bangladesh'],
    ['code' => 'BB', 'name' => 'Barbados'],
    ['code' => 'BY', 'name' => 'Belarus'],
    ['code' => 'BE', 'name' => 'Belgia'],
    ['code' => 'BZ', 'name' => 'Belize'],
    ['code' => 'BJ', 'name' => 'Benin'],
    ['code' => 'BM', 'name' => 'Bermuda'],
    ['code' => 'BT', 'name' => 'Bhutan'],
    ['code' => 'BO', 'name' => 'Bolivia'],
    ['code' => 'BA', 'name' => 'Bosnia dan Herzegovina'],
    ['code' => 'BW', 'name' => 'Botswana'],
    ['code' => 'BV', 'name' => 'Pulau Bouvet'],
    ['code' => 'BR', 'name' => 'Brasil'],
    ['code' => 'IO', 'name' => 'Wilayah Inggris di Samudra Hindia'],
    ['code' => 'BN', 'name' => 'Brunei'],
    ['code' => 'BG', 'name' => 'Bulgaria'],
    ['code' => 'BF', 'name' => 'Burkina Faso'],
    ['code' => 'BI', 'name' => 'Burundi'],
    ['code' => 'CV', 'name' => 'Tanjung Verde'],
    ['code' => 'KH', 'name' => 'Kamboja'],
    ['code' => 'CM', 'name' => 'Kamerun'],
    ['code' => 'CA', 'name' => 'Kanada'],
    ['code' => 'BQ', 'name' => 'Belanda Karibia'],
    ['code' => 'KY', 'name' => 'Kepulauan Cayman'],
    ['code' => 'CF', 'name' => 'Republik Afrika Tengah'],
    ['code' => 'TD', 'name' => 'Chad'],
    ['code' => 'CL', 'name' => 'Cile'],
    ['code' => 'CN', 'name' => 'Tiongkok'],
    ['code' => 'CX', 'name' => 'Pulau Natal'],
    ['code' => 'CC', 'name' => 'Kepulauan Cocos (Keeling)'],
    ['code' => 'CO', 'name' => 'Kolombia'],
    ['code' => 'KM', 'name' => 'Komoro'],
    ['code' => 'CG', 'name' => 'Kongo - Brazzaville'],
    ['code' => 'CD', 'name' => 'Kongo - Kinshasa'],
    ['code' => 'CK', 'name' => 'Kepulauan Cook'],
    ['code' => 'CR', 'name' => 'Kosta Rika'],
    ['code' => 'HR', 'name' => 'Kroasia'],
    ['code' => 'CU', 'name' => 'Kuba'],
    ['code' => 'CW', 'name' => 'Curaçao'],
    ['code' => 'CY', 'name' => 'Siprus'],
    ['code' => 'CZ', 'name' => 'Ceko'],
    ['code' => 'CI', 'name' => 'Côte d’Ivoire'],
    ['code' => 'DK', 'name' => 'Denmark'],
    ['code' => 'DJ', 'name' => 'Jibuti'],
    ['code' => 'DM', 'name' => 'Dominika'],
    ['code' => 'DO', 'name' => 'Republik Dominika'],
    ['code' => 'EC', 'name' => 'Ekuador'],
    ['code' => 'EG', 'name' => 'Mesir'],
    ['code' => 'SV', 'name' => 'El Salvador'],
    ['code' => 'GQ', 'name' => 'Guinea Ekuatorial'],
    ['code' => 'ER', 'name' => 'Eritrea'],
    ['code' => 'EE', 'name' => 'Estonia'],
    ['code' => 'SZ', 'name' => 'eSwatini'],
    ['code' => 'ET', 'name' => 'Etiopia'],
    ['code' => 'FK', 'name' => 'Kepulauan Falkland (Malvinas)'],
    ['code' => 'FO', 'name' => 'Kepulauan Faroe'],
    ['code' => 'FJ', 'name' => 'Fiji'],
    ['code' => 'FI', 'name' => 'Finlandia'],
    ['code' => 'FR', 'name' => 'Prancis'],
    ['code' => 'GF', 'name' => 'Guyana Prancis'],
    ['code' => 'PF', 'name' => 'Polinesia Prancis'],
    ['code' => 'TF', 'name' => 'Wilayah Selatan Prancis'],
    ['code' => 'GA', 'name' => 'Gabon'],
    ['code' => 'GM', 'name' => 'Gambia'],
    ['code' => 'GE', 'name' => 'Georgia'],
    ['code' => 'DE', 'name' => 'Jerman'],
    ['code' => 'GH', 'name' => 'Ghana'],
    ['code' => 'GI', 'name' => 'Gibraltar'],
    ['code' => 'GR', 'name' => 'Yunani'],
    ['code' => 'GL', 'name' => 'Greenland'],
    ['code' => 'GD', 'name' => 'Grenada'],
    ['code' => 'GP', 'name' => 'Guadeloupe'],
    ['code' => 'GU', 'name' => 'Guam'],
    ['code' => 'GT', 'name' => 'Guatemala'],
    ['code' => 'GG', 'name' => 'Guernsey'],
    ['code' => 'GN', 'name' => 'Guinea'],
    ['code' => 'GW', 'name' => 'Guinea-Bissau'],
    ['code' => 'GY', 'name' => 'Guyana'],
    ['code' => 'HT', 'name' => 'Haiti'],
    ['code' => 'HM', 'name' => 'Pulau Heard dan Kepulauan McDonald'],
    ['code' => 'HN', 'name' => 'Honduras'],
    ['code' => 'HK', 'name' => 'Hong Kong'],
    ['code' => 'HU', 'name' => 'Hungaria'],
    ['code' => 'IS', 'name' => 'Islandia'],
    ['code' => 'IN', 'name' => 'India'],
    ['code' => 'ID', 'name' => 'Indonesia'],
    ['code' => 'IR', 'name' => 'Iran'],
    ['code' => 'IQ', 'name' => 'Irak'],
    ['code' => 'IE', 'name' => 'Irlandia'],
    ['code' => 'IM', 'name' => 'Pulau Man'],
    ['code' => 'IL', 'name' => 'Israel'],
    ['code' => 'IT', 'name' => 'Italia'],
    ['code' => 'JM', 'name' => 'Jamaika'],
    ['code' => 'JP', 'name' => 'Jepang'],
    ['code' => 'JE', 'name' => 'Jersey'],
    ['code' => 'JO', 'name' => 'Yordania'],
    ['code' => 'KZ', 'name' => 'Kazakhstan'],
    ['code' => 'KE', 'name' => 'Kenya'],
    ['code' => 'KI', 'name' => 'Kiribati'],
    ['code' => 'KP', 'name' => 'Korea Utara'],
    ['code' => 'KR', 'name' => 'Korea Selatan'],
    ['code' => 'XK', 'name' => 'Kosovo'],
    ['code' => 'KW', 'name' => 'Kuwait'],
    ['code' => 'KG', 'name' => 'Kirgizstan'],
    ['code' => 'LA', 'name' => 'Laos'],
    ['code' => 'LV', 'name' => 'Latvia'],
    ['code' => 'LB', 'name' => 'Lebanon'],
    ['code' => 'LS', 'name' => 'Lesotho'],
    ['code' => 'LR', 'name' => 'Liberia'],
    ['code' => 'LY', 'name' => 'Libya'],
    ['code' => 'LI', 'name' => 'Liechtenstein'],
    ['code' => 'LT', 'name' => 'Lituania'],
    ['code' => 'LU', 'name' => 'Luksemburg'],
    ['code' => 'MO', 'name' => 'Makau'],
    ['code' => 'MK', 'name' => 'Makedonia Utara'],
    ['code' => 'MG', 'name' => 'Madagaskar'],
    ['code' => 'MW', 'name' => 'Malawi'],
    ['code' => 'MY', 'name' => 'Malaysia'],
    ['code' => 'MV', 'name' => 'Maladewa'],
    ['code' => 'ML', 'name' => 'Mali'],
    ['code' => 'MT', 'name' => 'Malta'],
    ['code' => 'MH', 'name' => 'Kepulauan Marshall'],
    ['code' => 'MQ', 'name' => 'Martinik'],
    ['code' => 'MR', 'name' => 'Mauritania'],
    ['code' => 'MU', 'name' => 'Mauritius'],
    ['code' => 'YT', 'name' => 'Mayotte'],
    ['code' => 'MX', 'name' => 'Meksiko'],
    ['code' => 'FM', 'name' => 'Mikronesia'],
    ['code' => 'MD', 'name' => 'Moldova'],
    ['code' => 'MC', 'name' => 'Monako'],
    ['code' => 'MN', 'name' => 'Mongolia'],
    ['code' => 'ME', 'name' => 'Montenegro'],
    ['code' => 'MS', 'name' => 'Montserrat'],
    ['code' => 'MA', 'name' => 'Maroko'],
    ['code' => 'MZ', 'name' => 'Mozambik'],
    ['code' => 'MM', 'name' => 'Myanmar (Burma)'],
    ['code' => 'NA', 'name' => 'Namibia'],
    ['code' => 'NR', 'name' => 'Nauru'],
    ['code' => 'NP', 'name' => 'Nepal'],
    ['code' => 'NL', 'name' => 'Belanda'],
    ['code' => 'NC', 'name' => 'Kaledonia Baru'],
    ['code' => 'NZ', 'name' => 'Selandia Baru'],
    ['code' => 'NI', 'name' => 'Nikaragua'],
    ['code' => 'NE', 'name' => 'Niger'],
    ['code' => 'NG', 'name' => 'Nigeria'],
    ['code' => 'NU', 'name' => 'Niue'],
    ['code' => 'NF', 'name' => 'Kepulauan Norfolk'],
    ['code' => 'MP', 'name' => 'Kepulauan Mariana Utara'],
    ['code' => 'NO', 'name' => 'Norwegia'],
    ['code' => 'OM', 'name' => 'Oman'],
    ['code' => 'PK', 'name' => 'Pakistan'],
    ['code' => 'PW', 'name' => 'Palau'],
    ['code' => 'PS', 'name' => 'Palestina'],
    ['code' => 'PA', 'name' => 'Panama'],
    ['code' => 'PG', 'name' => 'Papua Nugini'],
    ['code' => 'PY', 'name' => 'Paraguay'],
    ['code' => 'PE', 'name' => 'Peru'],
    ['code' => 'PH', 'name' => 'Filipina'],
    ['code' => 'PN', 'name' => 'Kepulauan Pitcairn'],
    ['code' => 'PL', 'name' => 'Polandia'],
    ['code' => 'PT', 'name' => 'Portugal'],
    ['code' => 'PR', 'name' => 'Puerto Riko'],
    ['code' => 'QA', 'name' => 'Qatar'],
    ['code' => 'RE', 'name' => 'Réunion'],
    ['code' => 'RO', 'name' => 'Rumania'],
    ['code' => 'RU', 'name' => 'Rusia'],
    ['code' => 'RW', 'name' => 'Rwanda'],
    ['code' => 'BL', 'name' => 'Saint Barthélemy'],
    ['code' => 'SH', 'name' => 'Saint Helena'],
    ['code' => 'KN', 'name' => 'Saint Kitts dan Nevis'],
    ['code' => 'LC', 'name' => 'Saint Lucia'],
    ['code' => 'MF', 'name' => 'Saint Martin'],
    ['code' => 'PM', 'name' => 'Saint Pierre dan Miquelon'],
    ['code' => 'VC', 'name' => 'Saint Vincent dan Grenadine'],
    ['code' => 'WS', 'name' => 'Samoa'],
    ['code' => 'SM', 'name' => 'San Marino'],
    ['code' => 'ST', 'name' => 'Sao Tome dan Principe'],
    ['code' => 'SA', 'name' => 'Arab Saudi'],
    ['code' => 'SN', 'name' => 'Senegal'],
    ['code' => 'RS', 'name' => 'Serbia'],
    ['code' => 'SC', 'name' => 'Seychelles'],
    ['code' => 'SL', 'name' => 'Sierra Leone'],
    ['code' => 'SG', 'name' => 'Singapura'],
    ['code' => 'SX', 'name' => 'Sint Maarten'],
    ['code' => 'SK', 'name' => 'Slovakia'],
    ['code' => 'SI', 'name' => 'Slovenia'],
    ['code' => 'SB', 'name' => 'Kepulauan Solomon'],
    ['code' => 'SO', 'name' => 'Somalia'],
    ['code' => 'ZA', 'name' => 'Afrika Selatan'],
    ['code' => 'GS', 'name' => 'Georgia Selatan & Kep. Sandwich Selatan'],
    ['code' => 'SS', 'name' => 'Sudan Selatan'],
    ['code' => 'ES', 'name' => 'Spanyol'],
    ['code' => 'LK', 'name' => 'Sri Lanka'],
    ['code' => 'SD', 'name' => 'Sudan'],
    ['code' => 'SR', 'name' => 'Suriname'],
    ['code' => 'SJ', 'name' => 'Kepulauan Svalbard dan Jan Mayen'],
    ['code' => 'SE', 'name' => 'Swedia'],
    ['code' => 'CH', 'name' => 'Swiss'],
    ['code' => 'SY', 'name' => 'Suriah'],
    ['code' => 'TW', 'name' => 'Taiwan'],
    ['code' => 'TJ', 'name' => 'Tajikistan'],
    ['code' => 'TZ', 'name' => 'Tanzania'],
    ['code' => 'TH', 'name' => 'Thailand'],
    ['code' => 'TL', 'name' => 'Timor Leste'],
    ['code' => 'TG', 'name' => 'Togo'],
    ['code' => 'TK', 'name' => 'Tokelau'],
    ['code' => 'TO', 'name' => 'Tonga'],
    ['code' => 'TT', 'name' => 'Trinidad dan Tobago'],
    ['code' => 'TN', 'name' => 'Tunisia'],
    ['code' => 'TR', 'name' => 'Turki'],
    ['code' => 'TM', 'name' => 'Turkmenistan'],
    ['code' => 'TC', 'name' => 'Kepulauan Turks dan Caicos'],
    ['code' => 'TV', 'name' => 'Tuvalu'],
    ['code' => 'UM', 'name' => 'Kepulauan Terluar AS'],
    ['code' => 'UG', 'name' => 'Uganda'],
    ['code' => 'UA', 'name' => 'Ukraina'],
    ['code' => 'AE', 'name' => 'Uni Emirat Arab'],
    ['code' => 'GB', 'name' => 'Inggris Raya'],
    ['code' => 'US', 'name' => 'Amerika Serikat'],
    ['code' => 'UY', 'name' => 'Uruguay'],
    ['code' => 'UZ', 'name' => 'Uzbekistan'],
    ['code' => 'VU', 'name' => 'Vanuatu'],
    ['code' => 'VA', 'name' => 'Vatikan'],
    ['code' => 'VE', 'name' => 'Venezuela'],
    ['code' => 'VN', 'name' => 'Vietnam'],
    ['code' => 'VG', 'name' => 'Kepulauan Virgin Britania Raya'],
    ['code' => 'VI', 'name' => 'Kepulauan Virgin Amerika Serikat'],
    ['code' => 'WF', 'name' => 'Kepulauan Wallis dan Futuna'],
    ['code' => 'EH', 'name' => 'Sahara Barat'],
    ['code' => 'YE', 'name' => 'Yaman'],
    ['code' => 'ZM', 'name' => 'Zambia'],
    ['code' => 'ZW', 'name' => 'Zimbabwe']
];
    Country::insert($countries);
    }
}
